image: ruby:2.6.5

stages:
  - test
  - deploy

cache:
  key: libs
  paths:
    - vendor/bundle
    - vendor/apt

before_script:
  - export LANG=C.UTF-8
  - export LANGUAGE=C.UTF-8
  - export LC_ALL=C.UTF-8
  - echo $RAILS_ENV
  - mkdir -p vendor/apt
  - apt-get update -qq && apt-get -o Dir::Cache::Archives="vendor/apt" install -y build-essential -qq libpq-dev cmake ghostscript libmagic-dev openssh-client curl
  - ruby -v
  - which ruby
  - bundle install --deployment --without production --jobs $(nproc) "${FLAGS[@]}"

test:
  stage: test
  services:
    - postgres:10.1
    - redis:4.0.2
  tags:
    - docker
  variables:
    RAILS_ENV: test
    RACK_ENV: test
    POSTGRES_DB: eusc_test
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
  script:
    - find ./config -name "*.yml.sample" -exec sh -c 'mv "$1" "${1%.yml.sample}.yml"' _ {} \;
    - bundle exec rake db:reset
    - bundle exec rake parallel:setup
    - bundle exec rake parallel:spec
