require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'Rakefile'

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/ClassLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 100

Layout/EmptyLines:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Documentation:
  Enabled: false
