development:
  adapter: async

test:
  adapter: test

integration:
  adapter: redis
  url: redis://redis:6379/2
  channel_prefix: istory_integration

staging:
  adapter: redis
  url: redis://redis:6379/3
  channel_prefix: istory_staging

production:
  adapter: redis
  url: redis://redis:6379/4
  channel_prefix: istory_production
